timeout: 0
serial: yes
serial_baudrate: 115200
default_entry: 1

/Praxis
protocol: linux
path: boot():/vmlinuz
module_path: boot():/initramfs.cpio.gz
cmdline: rdinit=/init praxis.live=1 console=tty0 loglevel=3
