#!/bin/sh

praxis_config_root() {
    printf '%s\n' "${PRAXIS_CONFIG_ROOT:-/etc/praxis}"
}

praxis_shell() {
    if [ -n "${PRAXIS_SHELL:-}" ] && [ -x "${PRAXIS_SHELL}" ]; then
        printf '%s\n' "${PRAXIS_SHELL}"
        return 0
    fi

    if [ -x /bin/bash ]; then
        printf '%s\n' /bin/bash
        return 0
    fi

    if [ -x /bin/sh ]; then
        printf '%s\n' /bin/sh
        return 0
    fi

    command -v sh
}

praxis_clear() {
    printf '\033c'
}

praxis_pause() {
    printf '\nPress Enter to continue... '
    read -r _
}

praxis_header() {
    praxis_clear
    printf 'Praxis\n'
    printf '%s\n\n' "$1"
}

praxis_load_core() {
    PRAXIS_CORE_FILE="$(praxis_config_root)/praxis.env"
    if [ -r "${PRAXIS_CORE_FILE}" ]; then
        . "${PRAXIS_CORE_FILE}"
    fi
}

praxis_valid_hostname() {
    PRAXIS_HOSTNAME_VALUE="${1:-}"

    if [ -z "${PRAXIS_HOSTNAME_VALUE}" ]; then
        return 1
    fi

    printf '%s\n' "${PRAXIS_HOSTNAME_VALUE}" | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$'
}

praxis_exec_shell() {
    PRAXIS_SHELL_PATH="$(praxis_shell)"
    export HOME="${HOME:-/root}"
    export PATH="/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    export PS1="${PRAXIS_PS1:-praxis# }"

    case "${PRAXIS_SHELL_PATH##*/}" in
        bash)
            if [ -r /etc/praxis/bashrc ]; then
                exec "${PRAXIS_SHELL_PATH}" --noprofile --rcfile /etc/praxis/bashrc -i
            fi
            exec "${PRAXIS_SHELL_PATH}" -i
            ;;
        sh)
            exec "${PRAXIS_SHELL_PATH}" -i
            ;;
        *)
            exec "${PRAXIS_SHELL_PATH}"
            ;;
    esac
}

praxis_is_mountpoint() {
    PRAXIS_MOUNT_TARGET="${1:-}"

    if [ -z "${PRAXIS_MOUNT_TARGET}" ]; then
        return 1
    fi

    if command -v mountpoint >/dev/null 2>&1; then
        mountpoint -q "${PRAXIS_MOUNT_TARGET}"
        return $?
    fi

    if command -v findmnt >/dev/null 2>&1; then
        findmnt -T "${PRAXIS_MOUNT_TARGET}" >/dev/null 2>&1
        return $?
    fi

    return 1
}

praxis_find_mount_source() {
    PRAXIS_FIND_TARGET="${1:-}"

    if [ -z "${PRAXIS_FIND_TARGET}" ]; then
        return 1
    fi

    if ! command -v findmnt >/dev/null 2>&1; then
        return 1
    fi

    findmnt -n -o SOURCE --target "${PRAXIS_FIND_TARGET}" 2>/dev/null || true
}

praxis_find_mount_fstype() {
    PRAXIS_FIND_TARGET="${1:-}"

    if [ -z "${PRAXIS_FIND_TARGET}" ]; then
        return 1
    fi

    if ! command -v findmnt >/dev/null 2>&1; then
        return 1
    fi

    findmnt -n -o FSTYPE --target "${PRAXIS_FIND_TARGET}" 2>/dev/null || true
}

praxis_fstab_spec() {
    PRAXIS_SPEC_TARGET="${1:-}"
    PRAXIS_SPEC_SOURCE="$(praxis_find_mount_source "${PRAXIS_SPEC_TARGET}")"

    if [ -z "${PRAXIS_SPEC_SOURCE}" ]; then
        return 1
    fi

    if command -v blkid >/dev/null 2>&1; then
        PRAXIS_SPEC_UUID="$(blkid -s UUID -o value "${PRAXIS_SPEC_SOURCE}" 2>/dev/null || true)"
        if [ -n "${PRAXIS_SPEC_UUID}" ]; then
            printf 'UUID=%s\n' "${PRAXIS_SPEC_UUID}"
            return 0
        fi
    fi

    printf '%s\n' "${PRAXIS_SPEC_SOURCE}"
}

praxis_write_fstab() {
    PRAXIS_FSTAB_TARGET_ROOT="${1:-}"
    PRAXIS_FSTAB_PATH="${PRAXIS_FSTAB_TARGET_ROOT}/etc/fstab"
    PRAXIS_ROOT_SPEC=''
    PRAXIS_ROOT_TYPE=''
    PRAXIS_BOOT_SPEC=''
    PRAXIS_BOOT_TYPE=''

    if [ -z "${PRAXIS_FSTAB_TARGET_ROOT}" ]; then
        return 1
    fi

    mkdir -p "${PRAXIS_FSTAB_TARGET_ROOT}/etc"

    if praxis_is_mountpoint "${PRAXIS_FSTAB_TARGET_ROOT}"; then
        PRAXIS_ROOT_SPEC="$(praxis_fstab_spec "${PRAXIS_FSTAB_TARGET_ROOT}" || true)"
        PRAXIS_ROOT_TYPE="$(praxis_find_mount_fstype "${PRAXIS_FSTAB_TARGET_ROOT}")"
    fi

    if praxis_is_mountpoint "${PRAXIS_FSTAB_TARGET_ROOT}/boot"; then
        PRAXIS_BOOT_SPEC="$(praxis_fstab_spec "${PRAXIS_FSTAB_TARGET_ROOT}/boot" || true)"
        PRAXIS_BOOT_TYPE="$(praxis_find_mount_fstype "${PRAXIS_FSTAB_TARGET_ROOT}/boot")"
    fi

    {
        printf '# Praxis fstab\n'
        printf '# Generated by praxis-install.\n'
        if [ -n "${PRAXIS_ROOT_SPEC}" ] && [ -n "${PRAXIS_ROOT_TYPE}" ]; then
            printf '%s / %s defaults 0 1\n' "${PRAXIS_ROOT_SPEC}" "${PRAXIS_ROOT_TYPE}"
        fi
        if [ -n "${PRAXIS_BOOT_SPEC}" ] && [ -n "${PRAXIS_BOOT_TYPE}" ]; then
            printf '%s /boot %s umask=0077 0 2\n' "${PRAXIS_BOOT_SPEC}" "${PRAXIS_BOOT_TYPE}"
        fi
    } > "${PRAXIS_FSTAB_PATH}"

    return 0
}

praxis_write_identity_files() {
    PRAXIS_ID_TARGET_ROOT="${1:-}"
    PRAXIS_ID_HOSTNAME="${2:-praxis}"

    if [ -z "${PRAXIS_ID_TARGET_ROOT}" ]; then
        return 1
    fi

    mkdir -p "${PRAXIS_ID_TARGET_ROOT}/etc"

    printf '%s\n' "${PRAXIS_ID_HOSTNAME}" > "${PRAXIS_ID_TARGET_ROOT}/etc/hostname"

    cat > "${PRAXIS_ID_TARGET_ROOT}/etc/hosts" <<EOF
127.0.0.1 localhost
127.0.1.1 ${PRAXIS_ID_HOSTNAME}
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

    return 0
}

praxis_write_loader_conf() {
    PRAXIS_LOADER_TARGET_ROOT="${1:-}"
    PRAXIS_LOADER_DEFAULT="${2:-praxis}"

    if [ -z "${PRAXIS_LOADER_TARGET_ROOT}" ]; then
        return 1
    fi

    mkdir -p "${PRAXIS_LOADER_TARGET_ROOT}/boot/loader"

    cat > "${PRAXIS_LOADER_TARGET_ROOT}/boot/loader/loader.conf" <<EOF
default ${PRAXIS_LOADER_DEFAULT}
timeout 0
console-mode max
editor no
EOF

    return 0
}

praxis_write_systemd_boot_entry() {
    PRAXIS_BOOT_TARGET_ROOT="${1:-}"
    PRAXIS_BOOT_ENTRY_NAME="${2:-praxis-dev}"
    PRAXIS_BOOT_ENTRY_TITLE="${3:-Praxis}"
    PRAXIS_BOOT_ENTRY_OPTIONS="${4:-rdinit=/init praxis.live=0 loglevel=3 console=tty0}"
    PRAXIS_BOOT_ENTRY_DIR="${PRAXIS_BOOT_ENTRY_DIR:-${PRAXIS_BOOT_TARGET_ROOT}/boot/loader/entries}"

    if [ -z "${PRAXIS_BOOT_TARGET_ROOT}" ]; then
        return 1
    fi

    mkdir -p "${PRAXIS_BOOT_ENTRY_DIR}"

    cat > "${PRAXIS_BOOT_ENTRY_DIR}/${PRAXIS_BOOT_ENTRY_NAME}.conf" <<EOF
title ${PRAXIS_BOOT_ENTRY_TITLE}
linux /praxis/vmlinuz
initrd /praxis/initramfs.cpio.gz
options ${PRAXIS_BOOT_ENTRY_OPTIONS}
EOF

    return 0
}

praxis_install_systemd_boot() {
    PRAXIS_BOOTCTL_TARGET_ROOT="${1:-}"
    PRAXIS_BOOTCTL_PATH="${2:-${PRAXIS_BOOTCTL_PATH:-${PRAXIS_BOOTCTL_TARGET_ROOT}/boot}}"

    if [ -z "${PRAXIS_BOOTCTL_TARGET_ROOT}" ]; then
        return 1
    fi

    if [ ! -d "${PRAXIS_BOOTCTL_PATH}" ]; then
        return 1
    fi

    if ! praxis_is_mountpoint "${PRAXIS_BOOTCTL_PATH}"; then
        return 1
    fi

    if ! command -v bootctl >/dev/null 2>&1; then
        return 1
    fi

    bootctl --boot-path="${PRAXIS_BOOTCTL_PATH}" --variables=no --graceful install >/dev/null 2>&1
}
